import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import { escapeHtml } from '../src/components/render.js';
const html = await readFile('dist/index.html', 'utf8');
const ids = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]));
for (const match of html.matchAll(/href="#([^"]+)"/g)) assert(ids.has(match[1]), `Missing anchor: ${match[1]}`);
for (const match of html.matchAll(/(?:src|href)="(assets\/[^"?#]+)"/g)) await access(`dist/${match[1]}`);
assert.match(html, /<script src="assets\/main\.js" type="module"><\/script>/);
assert.match(html, /<link rel="stylesheet" href="assets\/main\.css">/);
assert.match(html, /<img src="assets\/portrait\.jpg"/);
assert.match(html, /<link rel="icon" href="assets\/favicon\.svg"/);
assert.match(html, /id="cv"/);
assert.match(html, /<details class="cv-zip"><summary>/);
assert.match(html, /<iframe src="assets\/cv\.pdf#toolbar=0&amp;navpanes=0"/);
assert.match(html, /Unzip my CV to view/);
assert(!html.includes(' download=') && !html.includes('>Download CV<'));
await access('dist/assets/cv.pdf');
const clientScript = await readFile('dist/assets/main.js', 'utf8');
assert(!/\bimport\s*(?:\(|[{*'"])/.test(clientScript), 'Unexpected unresolved browser module import');
for (const id of ['about', 'projects', 'activity', 'experience', 'skills', 'education', 'cv', 'interests', 'contact']) assert(ids.has(id));
assert(html.includes('Asia Pacific Regulatory Centre') && html.includes('25 August 2026'));
assert(html.includes('GitHub contribution activity') && !html.includes('Academic progress') && !html.includes('GPA'));
assert(!html.includes('your.email') && !html.includes('[University]'));
assert.equal(escapeHtml('<script>"&'), '&lt;script&gt;&quot;&amp;');
console.log('Passed: section anchors, local assets, browser entry point, APRC content, placeholder and HTML escaping checks.');
