import { profile, projects, skills, experience, education } from './content.js';
import { escapeHtml as e, sectionHeading, projectCard, skillCard, experienceCard } from './components/render.js';
export function renderPage() {
return `<!doctype html>
<html lang="en" data-theme="dark">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="dark light"><meta name="description" content="Pranay Deep Singh — Software Engineering student at USP in Fiji. Explore coding projects, skills and project internship experience."><title>Pranay Deep Singh | Software Engineering</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/main.css"><script src="assets/main.js" type="module"></script></head>
<body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="container header-inner"><a class="brand" href="#home" aria-label="Pranay Deep Singh home">pds<span>.</span></a><button class="menu-button" type="button" aria-controls="navigation" aria-expanded="false">Menu</button><nav id="navigation" aria-label="Main navigation"><a href="#about">About</a><a href="#projects">Projects</a><a href="#activity">Activity</a><a href="#experience">Experience</a><a href="#skills">Skills</a><a href="#cv">CV</a><a href="#contact">Contact</a></nav><button class="theme-button" type="button" aria-label="Switch to light theme">Light mode</button></div></header>
<main id="main"><section class="hero container" id="home"><div class="hero-copy"><p class="eyebrow hero-eyebrow">${e(profile.role)} <span class="separator">/</span> Fiji</p><h1>Pranay<br>Deep Singh<span class="accent">.</span></h1><p class="hero-tagline">Curious mind.<br><span>Practical approach.</span></p><p class="hero-introduction">${e(profile.introduction)}</p><div class="actions"><a class="button primary" href="#projects">Explore my projects</a><a class="button secondary" href="${e(profile.github)}">GitHub / MisguidedMC</a></div></div><div class="hero-visual"><div class="portrait-frame"><img src="assets/portrait.jpg" alt="Pranay Deep Singh" width="328" height="441" fetchpriority="high"><div class="portrait-caption"><span>BASED IN</span><strong>Suva, Fiji</strong></div></div><div class="hero-note"><span class="note-marker">01 / IN PROGRESS</span><p>Learning through code.<br>Growing through experience.</p></div></div><div class="hero-bottom"><span>Software · Testing · Communication</span><a href="#about">Meet the person behind the code</a></div></section>
<div class="discipline-strip"><div class="container"><span>DEVELOP</span><span class="strip-plus">+</span><span>TEST</span><span class="strip-plus">+</span><span>DOCUMENT</span><span class="strip-plus">+</span><span>COLLABORATE</span></div></div>
<section class="section container" id="about">${sectionHeading('01','About','A developer in the making.')}<div class="about-grid"><p class="about-lead">Good software starts with understanding the problem.</p><div class="about-copy"><p>${e(profile.biography)}</p><p>${e(profile.perspective)}</p><div class="about-facts"><div><span class="eyebrow">Education</span><strong>University of the South Pacific</strong></div><div><span class="eyebrow">Current experience</span><strong>Project Intern · APRC</strong></div></div></div></div></section>
<section class="section project-section" id="projects"><div class="container">${sectionHeading('02','Selected work','Ideas into implementation.','A selection of coding projects, coursework and practice from my GitHub.')}<div class="project-filters" role="group" aria-label="Filter projects" hidden><button type="button" data-filter="all" aria-pressed="true">All work</button><button type="button" data-filter="projects" aria-pressed="false">Projects</button><button type="button" data-filter="coursework" aria-pressed="false">Coursework</button><button type="button" data-filter="practice" aria-pressed="false">Practice</button></div><p class="sr-only" id="filter-status" role="status"></p><div class="project-grid">${projects.map(projectCard).join('')}</div><div class="section-bottom"><span>More experiments live on GitHub.</span><a class="text-link" href="${e(profile.github)}?tab=repositories">Explore all repositories</a></div></div></section>
<section class="section container" id="activity"><div class="section-heading"><div><p class="eyebrow"><span>03</span> / GitHub activity</p><h2>Showing up, one commit at a time.</h2></div><p class="section-description">A snapshot of public contributions over the past year.</p></div><div class="contribution-panel" data-github-user="${e(profile.githubUsername)}"><div class="contribution-summary"><strong id="contribution-total" hidden></strong><span>Public contributions in the last year</span></div><div class="contribution-scroll" tabindex="0" aria-label="Scrollable GitHub contribution activity"><div class="contribution-grid" id="contribution-grid" role="img" aria-label="GitHub contribution activity is loading" hidden></div></div><div class="contribution-footer"><p class="contribution-status" id="contribution-status" role="status" aria-live="polite">Loading GitHub contribution activity…</p><div class="contribution-legend" id="contribution-legend" aria-label="Contribution levels" hidden><span>Less</span><i data-level="0"></i><i data-level="1"></i><i data-level="2"></i><i data-level="3"></i><i data-level="4"></i><span>More</span></div></div><p class="contribution-note">Public GitHub data via <a href="https://github-contributions-api.jogruber.de/" target="_blank" rel="noopener noreferrer">GitHub Contributions API</a>. Updates when its public profile data refreshes; private contributions may not appear.</p><a class="text-link" href="${e(profile.github)}" target="_blank" rel="noopener noreferrer">View my GitHub profile</a></div></section>
<section class="section container" id="experience">${sectionHeading('04','Experience','Beyond the code.','Reporting, testing and coordination have shaped how I approach project delivery.')}<div class="experience-list">${experience.map(experienceCard).join('')}</div></section>
<section class="section skills-section" id="skills"><div class="container">${sectionHeading('05','Skills','A growing toolkit.','Technical foundations paired with the skills that help a team work well.')}<div class="skill-grid">${skills.map(skillCard).join('')}</div></div></section>
<section class="section container" id="education">${sectionHeading('06','Education','Building the foundation.')}<div class="education-copy"><p class="eyebrow">${e(education.period)}</p><h3 class="degree-title">${e(education.degree)}</h3><p>${e(education.institution)}</p><p class="accent">${e(education.graduation)}</p><h4>Certifications · USP</h4><ul class="certifications">${education.certifications.map(c => `<li>${e(c)}</li>`).join('')}</ul></div></section>
<section class="section container" id="cv">${sectionHeading('07','Curriculum vitae','A closer look at my background.','Open the zip to view my CV.')}<details class="cv-zip"><summary><span class="cv-zipper" aria-hidden="true"><span class="cv-zipper-track"></span><span class="cv-zipper-pull"></span></span><span class="cv-zip-closed">Unzip my CV to view</span><span class="cv-zip-opened">CV open — zip it closed</span></summary><div class="cv-viewer"><iframe src="assets/cv.pdf#toolbar=0&amp;navpanes=0" title="Pranay Deep Singh’s curriculum vitae" loading="lazy"></iframe></div><p class="cv-note">CV preview. Browser PDF controls vary by device.</p></details></section>
<section class="section container" id="interests"><div class="interests-panel"><p class="eyebrow">Outside the coursework</p><h2>Still curious,<br>off the clock.</h2><div><p>I’m interested in how artificial intelligence can help people in everyday life and in more complex work.</p><p>Away from studying, I enjoy mobile games and the occasional Rubik’s cube — another kind of problem to solve.</p></div></div></section>
<section class="contact-section" id="contact"><div class="container contact-inner"><div><p class="eyebrow">08 / Contact</p><h2>Let’s build<br>something useful<span class="accent">.</span></h2><p>Interested in my work or have an opportunity in software or web development? I’d be glad to connect.</p></div><div class="contact-links"><a class="contact-email" href="mailto:${e(profile.email)}">${e(profile.email)}</a><a class="button secondary" href="${e(profile.github)}">Find me on GitHub</a><p>${e(profile.location)}</p></div></div></section></main>
<footer class="container footer"><a class="brand" href="#home">pds<span>.</span></a><p>© <span id="year">${new Date().getUTCFullYear()}</span> ${e(profile.name)}</p><a href="#home">Back to top</a></footer></body></html>`;
}
